CREATE TABLE LOGIN_USER (
    userId VARCHAR(10) PRIMARY KEY AUTO_INCREMENT,
    userName VARCHAR(99),
    password VARCHAR(8)
);
CREATE TABLE ITEM (
    id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(100),
	imageUrl VARCHAR(255),
	price INT
);