CREATE TABLE IF NOT EXISTS LOGIN_USER (
    userId VARCHAR(10) PRIMARY KEY,
    userName VARCHAR(99),
    password VARCHAR(8)
);
CREATE TABLE IF NOT EXISTS ITEM (
    id INT PRIMARY KEY,
	name VARCHAR(100),
	imageUrl VARCHAR(255),
	price INT
);